/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.room.management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.*;




/**
 *
 * @author Arun kundu
 */
public class admin extends javax.swing.JFrame {
     public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        insert = new javax.swing.JButton();
        show_data = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        telephone_text = new javax.swing.JTextField();
        room_charge_text = new javax.swing.JTextField();
        air = new javax.swing.JLabel();
        telephone = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        roomnum = new javax.swing.JLabel();
        floor = new javax.swing.JLabel();
        room_charge = new javax.swing.JLabel();
        id_text = new javax.swing.JTextField();
        bath = new javax.swing.JLabel();
        boy = new javax.swing.JLabel();
        room_num_text = new javax.swing.JTextField();
        boy_text = new javax.swing.JTextField();
        floor_text = new javax.swing.JTextField();
        room_size = new javax.swing.JLabel();
        air_text = new javax.swing.JComboBox();
        bath_text = new javax.swing.JComboBox();
        room_size_text = new javax.swing.JTextField();
        manager_table = new javax.swing.JButton();
        manager_db = new javax.swing.JButton();
        admin_db = new javax.swing.JButton();
        All_information = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        insert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        insert.setForeground(new java.awt.Color(0, 0, 153));
        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        show_data.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        show_data.setForeground(new java.awt.Color(204, 0, 204));
        show_data.setText("SHOW DATA");
        show_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_dataActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(51, 51, 0));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Room_No", "Floor_No", "Room size", "Air condition", "Attach bathroom", "Room charge", "Room boy", "Telephone_No"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        telephone_text.setForeground(new java.awt.Color(0, 51, 51));
        telephone_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephone_textActionPerformed(evt);
            }
        });

        room_charge_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room_charge_textActionPerformed(evt);
            }
        });

        air.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        air.setText("Air condition");

        telephone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telephone.setText("Telephone_No");

        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setText("ID");

        roomnum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        roomnum.setText("Room number");

        floor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        floor.setText("Floor number");

        room_charge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        room_charge.setText("Room charge");

        id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_textActionPerformed(evt);
            }
        });

        bath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bath.setText("Attach bath");

        boy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boy.setText("Room boy");

        room_num_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room_num_textActionPerformed(evt);
            }
        });

        boy_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boy_textActionPerformed(evt);
            }
        });

        floor_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor_textActionPerformed(evt);
            }
        });

        room_size.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        room_size.setText("Room size");

        air_text.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "Non AC" }));

        bath_text.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YES", "NO", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(roomnum, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(room_num_text, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(25, 25, 25)
                                    .addComponent(id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(room_size, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(floor_text, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(telephone, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addGap(32, 32, 32)
                                .addComponent(telephone_text, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bath, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(air, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(30, 30, 30)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(room_size_text, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(air_text, 0, 138, Short.MAX_VALUE)
                                    .addComponent(bath_text, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(room_charge, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(room_charge_text, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boy, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(boy_text, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomnum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room_num_text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floor_text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(room_size, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(room_size_text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(air, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(air_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(bath_text, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room_charge_text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room_charge, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boy, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boy_text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephone_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        manager_table.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manager_table.setText("Manager Table");
        manager_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manager_tableActionPerformed(evt);
            }
        });

        manager_db.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manager_db.setText("Manager database");
        manager_db.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manager_dbActionPerformed(evt);
            }
        });

        admin_db.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        admin_db.setText("Admin database");
        admin_db.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_dbActionPerformed(evt);
            }
        });

        All_information.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        All_information.setText("All information");
        All_information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                All_informationActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(51, 0, 51));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(show_data)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(admin_db)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(All_information, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(manager_table)
                            .addGap(18, 18, 18)
                            .addComponent(manager_db)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 403, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(show_data, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manager_db, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manager_table, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admin_db, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(All_information, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_textActionPerformed

    private void room_charge_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room_charge_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room_charge_textActionPerformed

    private void boy_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boy_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boy_textActionPerformed

    private void telephone_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephone_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephone_textActionPerformed

    private void show_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_dataActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dlm = (DefaultTableModel)table.getModel();
        
        try
        {
            String url="jdbc:derby://localhost:1527/project";
            String username="arun";
            String pass="1234";
            Connection con=DriverManager.getConnection(url, username, pass);
            Statement st=con.createStatement();
            String s="SELECT * FROM ADMIN";
            ResultSet rs=st.executeQuery(s);
            while(rs.next())
            {
                dlm.addRow( new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),});
            }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_show_dataActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dlm = (DefaultTableModel)table.getModel();
        if(table.getSelectedRow()==-1){
            if(table.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"Table is empty.");
            }
            else{
                JOptionPane.showMessageDialog(null, "You must select ID");
            }
        }
        else{
           dlm.setValueAt(id_text.getText(),table.getSelectedRow(),0);
           dlm.setValueAt(room_num_text.getText(),table.getSelectedRow(),1);
           dlm.setValueAt(floor_text.getText(),table.getSelectedRow(),2);
           dlm.setValueAt(room_size_text.getText(),table.getSelectedRow(),3);
           dlm.setValueAt(air_text.getSelectedItem().toString(),table.getSelectedRow(),4);
           dlm.setValueAt(bath_text.getSelectedItem().toString(),table.getSelectedRow(),5);
           dlm.setValueAt(room_charge_text.getText(),table.getSelectedRow(),6);
           dlm.setValueAt(boy_text.getText(),table.getSelectedRow(),7);
           dlm.setValueAt(telephone_text.getText(),table.getSelectedRow(),8);
        }
        
         try
        {
            String url="jdbc:derby://localhost:1527/project";
            String username="arun";
            String pass="1234";
            Connection con=DriverManager.getConnection(url, username, pass);
            Statement st=con.createStatement();
            String s="UPDATE ADMIN SET  ID='"+id_text.getText()+"',ROOM_NO='"+room_num_text.getText()+"',FLOOR_NO='"+floor_text.getText()+"',ROOM_SIZE='"+room_size_text.getText()+"',AIR='"+air_text.getSelectedItem().toString()+"',BATH='"+bath_text.getSelectedItem().toString()+"',CHARGE='"+room_charge_text.getText()+"',BOY='"+boy_text.getText()+"',TELEPHONE_NUM='"+telephone_text.getText()+"'"
                    + "WHERE ID='"+id_text.getText()+"'";
                    
             st.execute(s);
             
             JOptionPane.showMessageDialog(null,"Updated..");
        }
         catch(SQLException ex)
         {
             JOptionPane.showMessageDialog(null,ex.toString());
         }
    }//GEN-LAST:event_updateActionPerformed

    private void floor_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor_textActionPerformed

    private void room_num_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room_num_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room_num_textActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dlm= (DefaultTableModel)table.getModel();
        dlm.addRow(new Object[]{id_text.getText(),room_num_text.getText(),floor_text.getText(),room_size_text.getText(),air_text.getSelectedItem(),bath_text.getSelectedItem(),room_charge_text.getText(),boy_text.getText(),telephone_text.getText()});
        
        
        try
        {
            String url="jdbc:derby://localhost:1527/project";
            String username="arun";
            String pass="1234";
            Connection con=DriverManager.getConnection(url, username, pass);
            Statement st=con.createStatement();
            String s="INSERT INTO ADMIN(ID,ROOM_NO,FLOOR_NO,ROOM_SIZE,AIR,BATH,CHARGE,BOY,TELEPHONE_NUM)VALUES('"+id_text.getText()+"','"+room_num_text.getText()+"','"+floor_text.getText()+"','"+room_size_text.getText()+"','"+air_text.getSelectedItem()+"','"+bath_text.getSelectedItem()+"','"+room_charge_text.getText()+"','"+boy_text.getText()+"','"+telephone_text.getText()+"')";
                    
                    
            st.execute(s);
            
            JOptionPane.showMessageDialog(null,"Data added...");
            
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex.toString());
        }
        
        
        
        
    }//GEN-LAST:event_insertActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dlm = (DefaultTableModel)table.getModel();
        id_text.setText(dlm.getValueAt(table.getSelectedRow(), 0).toString());
        room_num_text.setText(dlm.getValueAt(table.getSelectedRow(), 1).toString());
        floor_text.setText(dlm.getValueAt(table.getSelectedRow(), 2).toString());
        room_size_text.setText(dlm.getValueAt(table.getSelectedRow(), 3).toString());
        air_text.setSelectedItem(dlm.getValueAt(table.getSelectedRow(), 4).toString());
        bath_text.setSelectedItem(dlm.getValueAt(table.getSelectedRow(), 5).toString());
        room_charge_text.setText(dlm.getValueAt(table.getSelectedRow(), 6).toString());
        boy_text.setText(dlm.getValueAt(table.getSelectedRow(), 7).toString());
        telephone_text.setText(dlm.getValueAt(table.getSelectedRow(), 8).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void manager_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manager_tableActionPerformed
        // TODO add your handling code here:
        HotelRoomManagement.managerpage.setVisible(true);
        
    }//GEN-LAST:event_manager_tableActionPerformed

    private void manager_dbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manager_dbActionPerformed
        // TODO add your handling code here:
        HotelRoomManagement.manager_db_page.setVisible(true);
    }//GEN-LAST:event_manager_dbActionPerformed

    private void admin_dbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_dbActionPerformed
        // TODO add your handling code here:
       initComponents();
       HotelRoomManagement.admin_db_page.setVisible(true);
       
       

    
    }//GEN-LAST:event_admin_dbActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dlm=(DefaultTableModel)table.getModel();
        try
        {
            String url="jdbc:derby://localhost:1527/project";
            String username="arun";
            String pass="1234";
            Connection con=DriverManager.getConnection(url, username, pass);
            Statement st=con.createStatement();
            String s="DELETE FROM ADMIN WHERE ID='"+id_text.getText()+"'";
            st.execute(s);
            dlm.removeRow(table.getSelectedRow());
            JOptionPane.showMessageDialog(null, "Data deleted...");
            id_text.setText(null);
            room_num_text.setText(null);
        floor_text.setText(null);
        room_size_text.setText(null);
        air_text.setSelectedItem(null);
        bath_text.setSelectedItem(null);
        room_charge_text.setText(null);
        boy_text.setText(null);
        telephone_text.setText(null);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void All_informationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_All_informationActionPerformed
        // TODO add your handling code here:
        HotelRoomManagement.all_information_db_page.setVisible(true);
    }//GEN-LAST:event_All_informationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton All_information;
    private javax.swing.JButton admin_db;
    private javax.swing.JLabel air;
    private javax.swing.JComboBox air_text;
    private javax.swing.JLabel bath;
    private javax.swing.JComboBox bath_text;
    private javax.swing.JLabel boy;
    private javax.swing.JTextField boy_text;
    private javax.swing.JButton delete;
    private javax.swing.JLabel floor;
    private javax.swing.JTextField floor_text;
    private javax.swing.JLabel id;
    private javax.swing.JTextField id_text;
    private javax.swing.JButton insert;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manager_db;
    private javax.swing.JButton manager_table;
    private javax.swing.JLabel room_charge;
    private javax.swing.JTextField room_charge_text;
    private javax.swing.JTextField room_num_text;
    private javax.swing.JLabel room_size;
    private javax.swing.JTextField room_size_text;
    private javax.swing.JLabel roomnum;
    private javax.swing.JButton show_data;
    private javax.swing.JTable table;
    private javax.swing.JLabel telephone;
    private javax.swing.JTextField telephone_text;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
                
}
