/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.room.management;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.*;

public class manager extends javax.swing.JFrame {

    /**
     * Creates new form manager
     */
    public manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_2 = new javax.swing.JTable();
        delete = new javax.swing.JButton();
        booking = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        show_all = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        leave = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        Booked = new javax.swing.JLabel();
        enter = new javax.swing.JLabel();
        adress_text = new javax.swing.JTextField();
        room_no_text = new javax.swing.JTextField();
        room_no = new javax.swing.JLabel();
        booked_text = new javax.swing.JComboBox();
        enter_text = new javax.swing.JTextField();
        name_text = new javax.swing.JTextField();
        adress = new javax.swing.JLabel();
        leave_text = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room_No", "Name", "Adress", "Entering_date", "Leaving_date", "Booked"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_2);

        delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 0, 0));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        booking.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        booking.setForeground(new java.awt.Color(0, 0, 255));
        booking.setText("Booking");
        booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Manager database");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        show_all.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        show_all.setText("Show_recent_all");
        show_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_allActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        leave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        leave.setText("leaving date");

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setText("Name");

        Booked.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Booked.setText("Booked");

        enter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enter.setText("Entering date");

        adress_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adress_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adress_textActionPerformed(evt);
            }
        });

        room_no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        room_no.setText("Room_No");

        booked_text.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YES", "NO" }));
        booked_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booked_textActionPerformed(evt);
            }
        });

        enter_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enter_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_textActionPerformed(evt);
            }
        });

        name_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_textActionPerformed(evt);
            }
        });

        adress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adress.setText("Adress");

        leave_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        leave_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leave_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(room_no, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(room_no_text, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(leave, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Booked, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(leave_text, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(booked_text, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(93, 93, 93))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enter_text, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adress_text))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(room_no_text, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room_no, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adress_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leave, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leave_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Booked, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(booked_text, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(booking, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(show_all)
                            .addGap(31, 31, 31)
                            .addComponent(jButton1))))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(booking, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(show_all, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adress_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adress_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adress_textActionPerformed

    private void leave_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leave_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leave_textActionPerformed

    private void enter_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enter_textActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dlM = (DefaultTableModel)table_2.getModel();
        try{
        String url= "jdbc:derby://localhost:1527/project";
        String username = "arun";
        String pass = "1234";
        Connection con=DriverManager.getConnection(url, username, pass);
        Statement st = con.createStatement();
        String s = "DELETE FROM MANAGER WHERE ROOM_NO = '"+room_no_text.getText()+"'";
        st.execute(s);
        dlM.removeRow(table_2.getSelectedRow());
        JOptionPane.showMessageDialog(null, "Data Deleted...");
        room_no_text.setText(null);
        name_text.setText(null);
        adress_text.setText(null);
        enter_text.setText(null);
        leave_text.setText(null);
        booked_text.setSelectedItem(null);
        
    }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void name_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_textActionPerformed

    private void bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dlM = (DefaultTableModel)table_2.getModel();
        dlM.addRow(new Object[]{room_no_text.getText(),name_text.getText(),adress_text.getText(),enter_text.getText(),leave_text.getText(),booked_text.getSelectedItem(),});
        
        try{
            String url = "jdbc:derby://localhost:1527/project";
            String username = "arun";
            String pass = "1234";
            Connection con = DriverManager.getConnection(url, username, pass);
            Statement st=con.createStatement();
            String s = "INSERT INTO MANAGER(ROOM_NO,NAME,ADRESS,ENTERING_DATE,LEAVING_DATE,BOOKED)VALUES('"+room_no_text.getText()+"','"+name_text.getText()+"','"+adress_text.getText()+"','"+enter_text.getText()+"','"+leave_text.getText()+"','"+booked_text.getSelectedItem()+"')";    
            st.execute(s);
            JOptionPane.showMessageDialog(null,"Data added....");
            
            }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
        try{
            String url = "jdbc:derby://localhost:1527/project";
            String username = "arun";
            String pass = "1234";
            Connection con = DriverManager.getConnection(url, username, pass);
            Statement st=con.createStatement();
            String s = "INSERT INTO ALL_INFORMATION(ROOM_NO,NAME,ADRESS,ENTERING_DATE,LEAVING_DATE,BOOKED)VALUES('"+room_no_text.getText()+"','"+name_text.getText()+"','"+adress_text.getText()+"','"+enter_text.getText()+"','"+leave_text.getText()+"','"+booked_text.getSelectedItem()+"')";    
            st.execute(s);
            JOptionPane.showMessageDialog(null,"Data added....");
            
            }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
        
    }//GEN-LAST:event_bookingActionPerformed

    private void booked_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booked_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booked_textActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HotelRoomManagement.manager_db_page.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void show_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_allActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dlM = (DefaultTableModel)table_2.getModel();
         try
        {
            String url="jdbc:derby://localhost:1527/project";
            String username="arun";
            String pass="1234";
            Connection con=DriverManager.getConnection(url, username, pass);
            Statement st=con.createStatement();
            String s="SELECT * FROM MANAGER";
            ResultSet rs=st.executeQuery(s);
            while(rs.next())
            {
                dlM.addRow( new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),});
            }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex.toString());
        } 
    }//GEN-LAST:event_show_allActionPerformed

    private void table_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dlM = (DefaultTableModel)table_2.getModel();
        room_no_text.setText(dlM.getValueAt(table_2.getSelectedRow(), 0).toString());
        name_text.setText(dlM.getValueAt(table_2.getSelectedRow(), 1).toString());
        adress_text.setText(dlM.getValueAt(table_2.getSelectedRow(), 2).toString());
        enter_text.setText(dlM.getValueAt(table_2.getSelectedRow(), 3).toString());
        leave_text.setText(dlM.getValueAt(table_2.getSelectedRow(), 4).toString());
        booked_text.setSelectedItem(dlM.getValueAt(table_2.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_table_2MouseClicked

           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Booked;
    private javax.swing.JLabel adress;
    private javax.swing.JTextField adress_text;
    private javax.swing.JComboBox booked_text;
    private javax.swing.JButton booking;
    private javax.swing.JButton delete;
    private javax.swing.JLabel enter;
    private javax.swing.JTextField enter_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leave;
    private javax.swing.JTextField leave_text;
    private javax.swing.JLabel name;
    private javax.swing.JTextField name_text;
    private javax.swing.JLabel room_no;
    private javax.swing.JTextField room_no_text;
    private javax.swing.JButton show_all;
    private javax.swing.JTable table_2;
    // End of variables declaration//GEN-END:variables
}
